version: '3'

services:
  prodavnicaDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - dbproddata:/var/lib/mysql
    networks:
      - myprodavnicanet
  prodavnicaDBMigration:
    image: prodavnicadbmigration
    environment:
      - DATABASE_PRODAVNICA_URL=prodavnicaDB
    depends_on:
      prodavnicaDB:
        condition: service_healthy
    networks:
      - myprodavnicanet

  customer:
    image: customer
    environment:
      - DATABASE_PRODAVNICA_URL=prodavnicaDB
    depends_on:
      - prodavnicaDBMigration
    ports:
      - 5003:5002
    networks:
      - myprodavnicanet

  courier:
    image: courier
    environment:
      - DATABASE_PRODAVNICA_URL=prodavnicaDB
    depends_on:
      - prodavnicaDBMigration
    ports:
    - 5004:5002
    networks:
      - myprodavnicanet

  owner:
    image: owner
    environment:
      - DATABASE_PRODAVNICA_URL=prodavnicaDB
    depends_on:
      - prodavnicaDBMigration
    ports:
      - 5005:5002
    networks:
      - myprodavnicanet
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - myprodavnicanet

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - 8082:8080
      - 7077:7077
    networks:
      - myprodavnicanet
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8083:8081
    networks:
      - myprodavnicanet
    environment:
      - SPARK_MASTER=spark://spark-master:7077
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8084:8081
    networks:
      - myprodavnicanet
    environment:
      - SPARK_MASTER=spark://spark-master:7077
  prodavnicaspark:
    image: prodavnicaspark
    environment:
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=prodavnicaspark
      - DATABASE_IP=prodavnicaDB
    ports:
      - 5006:5002
    networks:
      - myprodavnicanet


volumes:
  dbproddata:

networks:
  myprodavnicanet: